# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.12.2
    hooks:
      # The markdown-link-check can't access internal or private repos, see
      # .markdown_link_check_config.json on how to exclude more than github.com/arup-group
      - id: markdown-link-check
        args: [--quiet, --config=.markdown_link_check_config.json]
        exclude: \.excalidraw\.md$
  - repo: https://github.com/google/yamlfmt
    rev: v0.16.0
    hooks:
      - id: yamlfmt
        exclude: (.clang-(format|tidy)|tests/python/test_.*)
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.1
    hooks:
      - id: actionlint
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.33.0
    hooks:
      - id: check-jsonschema
        name: Validate markdownlint-cli2 config schema
        files: .markdownlint-cli2.jsonc
        args: [--schemafile, 'https://raw.githubusercontent.com/DavidAnson/markdownlint-cli2/main/schema/markdownlint-cli2-config-schema.json']
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2
        files: \.md$
        exclude: \.excalidraw\.md$
        args: [--config=.markdownlint-cli2.jsonc, --fix]
  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.33
    hooks:
      - id: pymarkdown
        name: PyMarkdown linter
        files: \.md$
        args: [fix]
        pass_filenames: true
        exclude: \.excalidraw\.md$
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.12.0-2
    hooks:
      - id: shfmt
        args: [-i, "4", -ci, -bn] # 4-space indent, simplify, bin ops on newline
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        args: [-x] # follow sourced files if resolvable
  - repo: https://github.com/openstack/bashate
    rev: 2.1.1
    hooks:
      - id: bashate
        args: [-i, E006] # ignore long lines
  # this should go last since it will fix line endings broken by other tools
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-case-conflict
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: end-of-file-fixer
        exclude: (\.svg$|\.png$)
      - id: check-yaml
      - id: check-xml
        exclude: .*\.svg$
      - id: check-json
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys, --indent=4]
        exclude: .*\.ipynb$
      - id: check-symlinks
      - id: debug-statements
      - id: fix-byte-order-marker
